name: Lint and Static Analysis

on:
  pull_request:
    paths:
      - main.py
      - context_chat_backend/**
      - reqs.txt
      - reqs.dev
  push:
    branches:
      - master
    paths:
      - main.py
      - context_chat_backend/**
      - reqs.txt
      - reqs.dev

jobs:
  analysis:
    runs-on: ubuntu-latest

    name: Lint and Static Analysis

    steps:
      - uses: actions/checkout@v4

      - name: Setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            reqs.txt
            reqs.dev

      - name: Install dependencies
        run: |
          pip install --no-deps -r reqs.txt
          pip install -r reqs.dev

      - name: Lint with Ruff
        run: |
          ls -la
          ruff check --output-format=github --config=pyproject.toml --no-cache

      - name: Static analysis with pyright
        run: |
          pyright
