name: My build action requiring more space

on: workflow_dispatch

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Free space before
        run: |
          echo "Free space before:"
          df -h

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          # need space in /var for Docker images
          root-reserve-mb:      30000
          remove-dotnet:        true
          remove-android:       true
          remove-haskell:       true
          remove-codeql:        true
          remove-docker-images: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Free space after
        run: |
          echo "Free space after:"
          df -h
